services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
    startCommand: gunicorn app:app
    envVars:
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
